# Generated by Django 4.1.5 on 2023-01-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=300)),
                ('moviePriority', models.IntegerField()),
                ('movieImg', models.ImageField(upload_to='task_img')),
                ('movieDate', models.DateField()),
                ('movieInfo', models.TextField()),
            ],
        ),
    ]
